Schedule metadata command log compaction

diff --git a/scripts/uat-s3-tests b/scripts/uat-s3-tests
--- a/scripts/uat-s3-tests
+++ b/scripts/uat-s3-tests
@@ -888,6 +888,13 @@ print_slowdown_summary() {
         local metadata_checkpoint_record_already_current
         local metadata_checkpoint_record_skipped_cadence
         local metadata_checkpoint_record_skipped_inactive
+        local metadata_checkpoint_record_skipped_empty
+        local metadata_checkpoint_record_skipped_stale_epoch
+        local metadata_checkpoint_record_compacted
+        local metadata_checkpoint_record_compaction_noop
+        local metadata_checkpoint_record_compaction_no_checkpoint
+        local metadata_checkpoint_record_compaction_pending
+        local metadata_checkpoint_record_compaction_failed
         local metadata_checkpoint_record_failed
         local metadata_checkpoint_record_limit_reached
         local metadata_checkpoint_record_scan_error
@@ -1017,6 +1024,13 @@ print_slowdown_summary() {
         metadata_checkpoint_record_already_current="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_already_current_total)"
         metadata_checkpoint_record_skipped_cadence="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_skipped_cadence_total)"
         metadata_checkpoint_record_skipped_inactive="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_skipped_inactive_total)"
+        metadata_checkpoint_record_skipped_empty="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_skipped_empty_total)"
+        metadata_checkpoint_record_skipped_stale_epoch="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_skipped_stale_epoch_total)"
+        metadata_checkpoint_record_compacted="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_compacted_total)"
+        metadata_checkpoint_record_compaction_noop="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_compaction_noop_total)"
+        metadata_checkpoint_record_compaction_no_checkpoint="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_compaction_no_checkpoint_total)"
+        metadata_checkpoint_record_compaction_pending="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_compaction_pending_total)"
+        metadata_checkpoint_record_compaction_failed="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_compaction_failed_total)"
         metadata_checkpoint_record_failed="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_failed_total)"
         metadata_checkpoint_record_limit_reached="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_limit_reached_total)"
         metadata_checkpoint_record_scan_error="$(latest_metric_sample_value "$metrics_log" metadata_command_checkpoint_record_scan_error_total)"
@@ -1090,7 +1104,7 @@ print_slowdown_summary() {
         echo "shard_backfill queue_depth=$shard_backfill_queue_depth event_total=$shard_backfill_event shards_written_total=$shard_backfill_shards_written" >&2
         echo "shard_backfill_candidate_scan scan_total=$shard_backfill_candidate_scan scanned_total=$shard_backfill_candidate_scanned current_epoch_total=$shard_backfill_candidate_current_epoch already_queued_total=$shard_backfill_candidate_already_queued already_complete_total=$shard_backfill_candidate_already_complete enqueued_total=$shard_backfill_candidate_enqueued unrecoverable_total=$shard_backfill_candidate_unrecoverable deferred_total=$shard_backfill_candidate_deferred failed_total=$shard_backfill_candidate_failed limit_reached_total=$shard_backfill_candidate_limit_reached scan_error_total=$shard_backfill_candidate_scan_error" >&2
         echo "shard_backfill_events durable_scan_no_claim=$shard_backfill_durable_scan_no_claim claim_started=$shard_backfill_claim_started started=$shard_backfill_started resolved_clean=$shard_backfill_resolved_clean backfilled=$shard_backfill_backfilled complete_succeeded=$shard_backfill_complete_succeeded complete_stale=$shard_backfill_complete_stale complete_failed=$shard_backfill_complete_failed stale_retry=$shard_backfill_stale_retry failed=$shard_backfill_failed record_error_failed=$shard_backfill_record_error_failed" >&2
-        echo "metadata_checkpoint_record scan_total=$metadata_checkpoint_record_scan scanned_total=$metadata_checkpoint_record_scanned recorded_total=$metadata_checkpoint_record_recorded already_current_total=$metadata_checkpoint_record_already_current skipped_cadence_total=$metadata_checkpoint_record_skipped_cadence skipped_inactive_total=$metadata_checkpoint_record_skipped_inactive failed_total=$metadata_checkpoint_record_failed limit_reached_total=$metadata_checkpoint_record_limit_reached scan_error_total=$metadata_checkpoint_record_scan_error" >&2
+        echo "metadata_checkpoint_record scan_total=$metadata_checkpoint_record_scan scanned_total=$metadata_checkpoint_record_scanned recorded_total=$metadata_checkpoint_record_recorded already_current_total=$metadata_checkpoint_record_already_current skipped_cadence_total=$metadata_checkpoint_record_skipped_cadence skipped_inactive_total=$metadata_checkpoint_record_skipped_inactive skipped_empty_total=$metadata_checkpoint_record_skipped_empty skipped_stale_epoch_total=$metadata_checkpoint_record_skipped_stale_epoch compacted_total=$metadata_checkpoint_record_compacted compaction_noop_total=$metadata_checkpoint_record_compaction_noop compaction_no_checkpoint_total=$metadata_checkpoint_record_compaction_no_checkpoint compaction_pending_total=$metadata_checkpoint_record_compaction_pending compaction_failed_total=$metadata_checkpoint_record_compaction_failed failed_total=$metadata_checkpoint_record_failed limit_reached_total=$metadata_checkpoint_record_limit_reached scan_error_total=$metadata_checkpoint_record_scan_error" >&2
         echo "background_work event_total=$background_work_event active=$background_work_active finished=$background_work_finished elapsed_us_total=$background_work_elapsed_us" >&2
         echo "background_work_classes known_damage_repair_admitted=$background_work_known_damage_admitted known_damage_repair_denied_limit=$background_work_known_damage_denied_limit known_damage_repair_denied_foreground_pressure=$background_work_known_damage_denied_foreground_pressure known_damage_repair_denied_backlog_pressure=$background_work_known_damage_denied_backlog_pressure known_damage_repair_finished=$background_work_known_damage_finished backfill_candidate_scan_admitted=$background_work_backfill_candidate_scan_admitted backfill_candidate_scan_denied_limit=$background_work_backfill_candidate_scan_denied_limit backfill_candidate_scan_denied_foreground_pressure=$background_work_backfill_candidate_scan_denied_foreground_pressure backfill_candidate_scan_denied_backlog_pressure=$background_work_backfill_candidate_scan_denied_backlog_pressure backfill_candidate_scan_finished=$background_work_backfill_candidate_scan_finished routine_backfill_admitted=$background_work_routine_backfill_admitted routine_backfill_denied_limit=$background_work_routine_backfill_denied_limit routine_backfill_denied_foreground_pressure=$background_work_routine_backfill_denied_foreground_pressure routine_backfill_denied_backlog_pressure=$background_work_routine_backfill_denied_backlog_pressure routine_backfill_finished=$background_work_routine_backfill_finished routine_metadata_checkpoint_admitted=$background_work_routine_metadata_checkpoint_admitted routine_metadata_checkpoint_denied_limit=$background_work_routine_metadata_checkpoint_denied_limit routine_metadata_checkpoint_denied_foreground_pressure=$background_work_routine_metadata_checkpoint_denied_foreground_pressure routine_metadata_checkpoint_denied_backlog_pressure=$background_work_routine_metadata_checkpoint_denied_backlog_pressure routine_metadata_checkpoint_finished=$background_work_routine_metadata_checkpoint_finished reclaim_cleanup_admitted=$background_work_reclaim_cleanup_admitted reclaim_cleanup_denied_limit=$background_work_reclaim_cleanup_denied_limit reclaim_cleanup_denied_foreground_pressure=$background_work_reclaim_cleanup_denied_foreground_pressure reclaim_cleanup_denied_backlog_pressure=$background_work_reclaim_cleanup_denied_backlog_pressure reclaim_cleanup_finished=$background_work_reclaim_cleanup_finished lifecycle_cleanup_admitted=$background_work_lifecycle_cleanup_admitted lifecycle_cleanup_denied_limit=$background_work_lifecycle_cleanup_denied_limit lifecycle_cleanup_denied_foreground_pressure=$background_work_lifecycle_cleanup_denied_foreground_pressure lifecycle_cleanup_denied_backlog_pressure=$background_work_lifecycle_cleanup_denied_backlog_pressure lifecycle_cleanup_finished=$background_work_lifecycle_cleanup_finished stream_session_cleanup_admitted=$background_work_stream_session_cleanup_admitted stream_session_cleanup_denied_limit=$background_work_stream_session_cleanup_denied_limit stream_session_cleanup_denied_foreground_pressure=$background_work_stream_session_cleanup_denied_foreground_pressure stream_session_cleanup_denied_backlog_pressure=$background_work_stream_session_cleanup_denied_backlog_pressure stream_session_cleanup_finished=$background_work_stream_session_cleanup_finished opportunistic_scan_admitted=$background_work_opportunistic_scan_admitted opportunistic_scan_denied_limit=$background_work_opportunistic_scan_denied_limit opportunistic_scan_denied_foreground_pressure=$background_work_opportunistic_scan_denied_foreground_pressure opportunistic_scan_denied_backlog_pressure=$background_work_opportunistic_scan_denied_backlog_pressure opportunistic_scan_finished=$background_work_opportunistic_scan_finished" >&2
         echo "metadata_recovery_top admission" >&2
